### run with rest client in vscode

POST https://pitacofunctionapi.azurewebsites.net/api/getComments HTTP/1.1
content-type: application/json

"https://pitaco.blob.core.windows.net/pitaco-jsclient/javascriptTest.html"


############################

POST https://localhost:55001/api/addComment HTTP/1.1
content-type: application/json

{
    "wskey": "tiagodallignacom",
    "url": "https://pitaco.blob.core.windows.net/pitaco-jsclient/javascriptTest.html",
    "text": "the test comment",
    "author": "the test author",
    "key": "1",
    "timestamp": "2021-01-01"
}